#!/usr/bin/env python3
"""
🎨 Kids Gallery — Add Artwork Tool
════════════════════════════════════
Drop image files into the /images folder, then run this script.
It will detect new images and guide you through adding them to the gallery.

Usage:
    python add_artwork.py
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# ── Paths ────────────────────────────────────────────────
SCRIPT_DIR   = Path(__file__).parent
JSON_FILE    = SCRIPT_DIR / "artworks.json"
JS_FILE      = SCRIPT_DIR / "artworks.js"
IMAGES_DIR   = SCRIPT_DIR / "images"
IMAGE_EXTS   = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif"}

# ── Colors for terminal output ────────────────────────────
RESET  = "\033[0m"
BOLD   = "\033[1m"
GREEN  = "\033[92m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
RED    = "\033[91m"
DIM    = "\033[2m"

def c(text, color): return f"{color}{text}{RESET}"
def banner(msg):    print(f"\n{BOLD}{CYAN}{'═' * 50}{RESET}\n  {BOLD}{msg}{RESET}\n{BOLD}{CYAN}{'═' * 50}{RESET}\n")
def success(msg):   print(f"  {GREEN}✅ {msg}{RESET}")
def warn(msg):      print(f"  {YELLOW}⚠️  {msg}{RESET}")
def info(msg):      print(f"  {CYAN}ℹ️  {msg}{RESET}")
def err(msg):       print(f"  {RED}❌ {msg}{RESET}")

# ── Helpers ───────────────────────────────────────────────
def slugify(text: str) -> str:
    """Convert a filename or title to a URL-safe id."""
    text = Path(text).stem  # strip extension
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s\-]", "", text)
    text = re.sub(r"[\s_]+", "-", text.strip())
    text = re.sub(r"-+", "-", text)
    return text

def load_data() -> dict:
    if JSON_FILE.exists():
        with open(JSON_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {
        "gallery_title":    "Our Little Artists 🎨",
        "gallery_subtitle": "A collection of original artworks",
        "artworks":         []
    }

def save_data(data: dict):
    with open(JSON_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def regenerate_js(data: dict):
    """Rebuild artworks.js from artworks.json — do not edit artworks.js manually."""
    artworks_js = []
    for a in data["artworks"]:
        # Escape backticks and backslashes for JS template safety
        desc = a["description"].replace("\\", "\\\\").replace("`", "\\`")
        artworks_js.append(
            f"  {{\n"
            f"    id:          \"{a['id']}\",\n"
            f"    title:       \"{a['title']}\",\n"
            f"    date:        \"{a['date']}\",\n"
            f"    image:       \"{a['image']}\",\n"
            f"    description: `{desc}`\n"
            f"  }}"
        )

    js = (
        "// ═══════════════════════════════════════════════════════\n"
        "//  AUTO-GENERATED — do not edit this file manually!\n"
        "//  To add artworks, run:  python add_artwork.py\n"
        "// ═══════════════════════════════════════════════════════\n\n"
        f"const GALLERY_TITLE    = \"{data['gallery_title']}\";\n"
        f"const GALLERY_SUBTITLE = \"{data['gallery_subtitle']}\";\n\n"
        "const ARTWORKS = [\n"
        + ",\n".join(artworks_js) + "\n"
        "];\n"
    )
    with open(JS_FILE, "w", encoding="utf-8") as f:
        f.write(js)

def prompt(label: str, default: str = "", required: bool = True) -> str:
    """Prompt the user for input with an optional default."""
    hint = f" [{default}]" if default else ""
    while True:
        val = input(f"  {BOLD}{label}{hint}:{RESET} ").strip()
        if not val and default:
            return default
        if val or not required:
            return val
        print(f"  {YELLOW}This field is required.{RESET}")

def prompt_multiline(label: str) -> str:
    """Prompt for a description (supports multi-sentence, ends on blank line)."""
    print(f"  {BOLD}{label}{RESET} {DIM}(press Enter twice when done){RESET}")
    lines = []
    while True:
        line = input("  > ")
        if line == "" and lines:
            break
        lines.append(line)
    return " ".join(lines).strip()

def get_default_date() -> str:
    now = datetime.now()
    return now.strftime("%B %Y")  # e.g. "March 2026"

def detect_new_images(data: dict) -> list[Path]:
    """Find images in /images that don't have an entry in the data yet."""
    if not IMAGES_DIR.exists():
        IMAGES_DIR.mkdir()
        return []
    existing_images = {a["image"] for a in data["artworks"]}
    new_images = []
    for f in sorted(IMAGES_DIR.iterdir()):
        if f.suffix.lower() in IMAGE_EXTS:
            rel_path = f"images/{f.name}"
            if rel_path not in existing_images:
                new_images.append(f)
    return new_images

def add_image(data: dict, image_path: Path) -> dict:
    """Interactively collect info for one new image and return the entry."""
    rel_path  = f"images/{image_path.name}"
    suggested_id    = slugify(image_path.name)
    suggested_title = image_path.stem.replace("-", " ").replace("_", " ").title()
    suggested_date  = get_default_date()

    print(f"\n  {BOLD}🖼️  Image:{RESET} {CYAN}{image_path.name}{RESET}")
    print(f"  {DIM}{'─' * 44}{RESET}")

    title = prompt("Title",       default=suggested_title)
    date  = prompt("Date created", default=suggested_date)
    desc  = prompt_multiline("Description")

    # Ensure id is unique
    art_id = suggested_id
    existing_ids = {a["id"] for a in data["artworks"]}
    if art_id in existing_ids:
        art_id = art_id + f"-{len(data['artworks']) + 1}"

    return {
        "id":          art_id,
        "title":       title,
        "date":        date,
        "image":       rel_path,
        "description": desc
    }

def list_artworks(data: dict):
    artworks = data["artworks"]
    if not artworks:
        warn("No artworks in the gallery yet.")
        return
    print(f"\n  {BOLD}{'#':<4} {'Title':<30} {'Date':<15} {'Image'}{RESET}")
    print(f"  {'─' * 65}")
    for i, a in enumerate(artworks, 1):
        img_exists = (SCRIPT_DIR / a["image"]).exists()
        img_icon   = "✅" if img_exists else "❌"
        print(f"  {str(i):<4} {a['title']:<30} {a['date']:<15} {img_icon} {a['image']}")

def delete_artwork(data: dict):
    artworks = data["artworks"]
    if not artworks:
        warn("No artworks to delete.")
        return data
    list_artworks(data)
    print()
    raw = prompt("Enter artwork number to delete (or 0 to cancel)", required=False)
    if not raw or raw == "0":
        return data
    try:
        idx = int(raw) - 1
        if idx < 0 or idx >= len(artworks):
            err("Invalid number.")
            return data
        removed = artworks.pop(idx)
        success(f"Removed \"{removed['title']}\" from the gallery.")
        info("(The image file was NOT deleted from /images)")
    except ValueError:
        err("Please enter a valid number.")
    return data

def edit_settings(data: dict) -> dict:
    print(f"\n  Current title:    {CYAN}{data['gallery_title']}{RESET}")
    print(f"  Current subtitle: {CYAN}{data['gallery_subtitle']}{RESET}\n")
    data["gallery_title"]    = prompt("Gallery title",    default=data["gallery_title"])
    data["gallery_subtitle"] = prompt("Gallery subtitle", default=data["gallery_subtitle"])
    return data

# ── Main Menu ─────────────────────────────────────────────
def main():
    banner("🎨 Kids Gallery — Artwork Manager")

    # Ensure images folder exists
    IMAGES_DIR.mkdir(exist_ok=True)

    data = load_data()

    while True:
        # Auto-detect new images
        new_images = detect_new_images(data)

        print(f"\n  Gallery: {BOLD}{data['gallery_title']}{RESET}")
        print(f"  Artworks in gallery: {BOLD}{CYAN}{len(data['artworks'])}{RESET}")
        if new_images:
            print(f"  {GREEN}{BOLD}🆕 {len(new_images)} new image(s) detected in /images!{RESET}")
        print()
        print(f"  {BOLD}What would you like to do?{RESET}")
        print(f"  {CYAN}1{RESET}  Add new artwork(s){' ' + GREEN + f'← {len(new_images)} new image(s) waiting!' + RESET if new_images else ''}")
        print(f"  {CYAN}2{RESET}  List all artworks")
        print(f"  {CYAN}3{RESET}  Delete an artwork")
        print(f"  {CYAN}4{RESET}  Edit gallery title / subtitle")
        print(f"  {CYAN}5{RESET}  Rebuild artworks.js (without changes)")
        print(f"  {CYAN}0{RESET}  Exit")
        print()

        choice = input(f"  {BOLD}Your choice:{RESET} ").strip()

        if choice == "1":
            if not new_images:
                warn("No new images found in the /images folder.")
                info("Drop image files there first, then come back.")
            else:
                print(f"\n  Found {len(new_images)} new image(s). Let's add them!\n")
                added = 0
                for img in new_images:
                    entry = add_image(data, img)
                    data["artworks"].append(entry)
                    save_data(data)
                    regenerate_js(data)
                    success(f"Added \"{entry['title']}\" to the gallery!")
                    added += 1
                    if added < len(new_images):
                        cont = input(f"\n  {BOLD}Add next image? (Y/n):{RESET} ").strip().lower()
                        if cont == "n":
                            break
                print()
                success(f"Done! {added} artwork(s) added. artworks.js has been updated.")

        elif choice == "2":
            list_artworks(data)

        elif choice == "3":
            data = delete_artwork(data)
            save_data(data)
            regenerate_js(data)
            success("artworks.js has been updated.")

        elif choice == "4":
            data = edit_settings(data)
            save_data(data)
            regenerate_js(data)
            success("Gallery settings updated. artworks.js has been updated.")

        elif choice == "5":
            regenerate_js(data)
            success("artworks.js rebuilt from artworks.json.")

        elif choice == "0":
            print(f"\n  {BOLD}Goodbye! 🎨{RESET}\n")
            sys.exit(0)

        else:
            warn("Please enter a number from the menu.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n  {DIM}Cancelled. Goodbye!{RESET}\n")
        sys.exit(0)
