// ═══════════════════════════════════════════════════════
//  AUTO-GENERATED — do not edit this file manually!
//  To add artworks, run:  python add_artwork.py
// ═══════════════════════════════════════════════════════

const GALLERY_TITLE    = "Our Little Artists 🎨";
const GALLERY_SUBTITLE = "A collection of original artworks";

const ARTWORKS = [
  {
    id:          "780929262774348",
    title:       "Cool_Panda",
    date:        "forgetton",
    image:       "images/780929262.774348.jpg",
    description: `A happy and cool panda`
  }
];
